#!/bin/bash

function gifify() {
  if [[ -n "$1" ]]; then
	  ffmpeg -i "$1" -pix_fmt rgb24 -r 10 -f gif - | gifsicle --optimize=3 --delay=3 > "$1.gif"
  else
	echo "Proper usage: gifify <input_movie.mov>"
  fi
}

gifify
